### ISSUE TITLE
Change out photos for Lion and Orangutan

### ISSUE THREAD

**Issue by cgsmith** [zoological-society-of-milwaukee/zooview.tv#31]
There is no male lion at the Zoo or baby Orangutan. Can you use Lioness/Hyena for the Lion picture? Can you use just an Orangutan without a baby for the Orangutan picture?

**Comment by cgsmith** [comment]
These can be used.

![animal-gd75e2ca91_1920](https://user-images.githubusercontent.com/570018/135319903-e55a909c-acd3-4825-aa11-62ea2cdc4732.jpg)
![lion-gc236a687d_1920](https://user-images.githubusercontent.com/570018/135319905-09a5ec0f-8183-4941-9f04-72b71368be66.jpg)

**Comment by bkeating** [comment]
I see my assignment and will reply back with change.

Probably only repo on GitHub to have such photos. awww.

**Comment by cgsmith** [comment]
@bkeating since the cam is Lion/Hyena... maybe there is a way to combine the image to show both
![kruger-gce5180602_1920](https://user-images.githubusercontent.com/570018/135320540-34450ef8-c445-4ac6-b0e8-e181141a10ea.jpg)
?

**Comment by bkeating** [comment]
just so as long as i am not responsible for anything that may happen to
either animal by putting them so close together. ;)
